/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface AppArticle {
    'title': string;
  }
  interface AppArticleAttributes extends StencilHTMLAttributes {
    'title'?: string;
  }

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'history': RouterHistory;
    'iden': String;
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'iden'?: String;
    'match'?: MatchResults;
  }

  interface AppRoot {
    'first': string;
    'last': string;
  }
  interface AppRootAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
    'onBackgroundToggle'?: (event: CustomEvent) => void;
  }

  interface EditArticle {
    'match': MatchResults;
  }
  interface EditArticleAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppArticle': Components.AppArticle;
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'EditArticle': Components.EditArticle;
  }

  interface StencilIntrinsicElements {
    'app-article': Components.AppArticleAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'edit-article': Components.EditArticleAttributes;
  }


  interface HTMLAppArticleElement extends Components.AppArticle, HTMLStencilElement {}
  var HTMLAppArticleElement: {
    prototype: HTMLAppArticleElement;
    new (): HTMLAppArticleElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLEditArticleElement extends Components.EditArticle, HTMLStencilElement {}
  var HTMLEditArticleElement: {
    prototype: HTMLEditArticleElement;
    new (): HTMLEditArticleElement;
  };

  interface HTMLElementTagNameMap {
    'app-article': HTMLAppArticleElement
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'edit-article': HTMLEditArticleElement
  }

  interface ElementTagNameMap {
    'app-article': HTMLAppArticleElement;
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'edit-article': HTMLEditArticleElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
